[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["**/__pycache__"]

[project]
name = "flathub_repro_checker"
version = "0.2.2"
description = "A tool to rebuild Flatpak apps published on Flathub and compare reproducibility using diffoscope"
authors = [
  {name = "bbhtt", email = "bbhtt@bbhtt.in"},
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "<4.0,>=3.10"
dependencies = []

[project.urls]
Homepage = "https://github.com/flathub-infra/flathub-repro-checker"
Repository = "https://github.com/flathub-infra/flathub-repro-checker.git"
Issues = "https://github.com/flathub-infra/flathub-repro-checker/issues"

[project.scripts]
flathub-repro-checker = "flathub_repro_checker.__main__:main"

[project.optional-dependencies]
s3upload = [
  "boto3>=1.39.10,<2.0.0",
]

[dependency-groups]
dev = [
    "mypy<2.0.0,>=1.11.2",
    "ruff<1.0.0,>=0.6.7",
    "pre-commit<4.0.0,>=3.8.0",
    "boto3-stubs[s3]>=1.39.10,<2.0.0",
    "pytest>=8.3.3,<10.0.0",
]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
extra_checks = true
no_implicit_optional = true
no_implicit_reexport = true
show_error_codes = true
strict = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.ruff]
line-length = 100
include = ["*.py"]
target-version = "py310"

[tool.ruff.lint]
select = [
  "A",
  "ARG",
  "B",
  "C4",
  "DTZ",
  "E",
  "ERA",
  "F",
  "I",
  "ICN",
  "PIE",
  "PL",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "T201",
  "UP",
  "W",
]

ignore = [
  "PLR2004",
  "PLR0911",
  "PLR0912",
  "PLR0913",
  "PLR0915",
  "S105",
  "S607",
  "S603",
]

[tool.ruff.format]
line-ending = "lf"
quote-style = "double"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101", "S103", "S108"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-m 'not integration'"
markers = [
    "integration: slow integration tests requires network access",
]
